package sty13;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;

public class NaszeOkienka {
    private JPanel PanelGlowny;
    private JButton clickMeButton;
    private JTextField textField1;
    private int counter = 0;

    public NaszeOkienka() {
        $$$setupUI$$$();
        textField1.addMouseMotionListener(new MouseMotionAdapter() {
        });
        clickMeButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                textField1.setText(String.valueOf(counter++));
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("NaszeOkienka");
        frame.setContentPane(new NaszeOkienka().PanelGlowny);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        PanelGlowny = new JPanel();
        PanelGlowny.setLayout(new GridBagLayout());
        PanelGlowny.setBackground(new Color(-15524031));
        PanelGlowny.setForeground(new Color(-5223237));
        clickMeButton.setBackground(new Color(-12512235));
        clickMeButton.setEnabled(true);
        clickMeButton.setForeground(new Color(-11945050));
        clickMeButton.setHideActionText(false);
        clickMeButton.setText("Click me!");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        PanelGlowny.add(clickMeButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        PanelGlowny.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        PanelGlowny.add(spacer2, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        PanelGlowny.add(textField1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelGlowny;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
